<h1 style="color:red">Predicting without using pipelines</h1>

In [ ]:
# we gonna add a new passenger details, and use the objects stored in 'models/....' 
# and then we will precict whether the passenger would survive or not

In [1]:
import pickle
import numpy as np

<h3 style="color:brown">Load saved encoders and trained model</h3>

In [3]:
# importing objects from the 'models/...' with the same name as used while exporting
# these objects will behave same as they where behaving in the original file 

ohe_sex = pickle.load(open('models/ohe_sex.pkl', 'rb')) 
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
dt = pickle.load(open('models/decision_tree.pkl', 'rb'))

<h3 style="color:brown">Load saved encoders and trained model</h3>

In [6]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked 
test_input = np.array([2,'male', 34, 1,2, 36.2, 'S'], dtype=object).reshape(1,7)

In [7]:
test_input

array([[2, 'male', 34, 1, 2, 36.2, 'S']], dtype=object)

<h3 style="color:brown">Apply OHE</h3>

In [11]:
# apply all the preprocesing steps which you earlier applied on the train data,
# like imputer, OHE, then concatenate and then apply decision tree

In [23]:
# Loads the trained OneHotEncoder used for the 'Sex' column

# better practice to use column no. like (1 -> sex) instead of using like df['sex'], 
test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(1,1)) 
# This warning occurs because the encoder was trained using a DataFrame column name (Sex), 
# but during prediction you passed a NumPy array without column names.

C:\Users\rupes\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [16]:
test_input_sex      # OHE encoded for 'male'

array([[0, 1]])

In [17]:
test_input_embarked = ohe_embarked.transform(test_input[:, -1].reshape(1,1))

In [18]:
test_input_embarked      # OHE encoded for 'S'

array([[0, 0, 1]])

In [31]:
test_input_age = test_input[:, 2].reshape(1,1)

In [32]:
test_input_age

array([[34]], dtype=object)

<h3 style="color:brown">Concatenating all numpy arrays</h3>

In [33]:
test_input_tnf = np.concat((test_input_age, test_input_sex, test_input[:, [0,3,4,5]], test_input_embarked), axis=1)

In [34]:
display(test_input_tnf.shape)
test_input_tnf

(1, 10)

array([[34, 0, 1, 2, 1, 2, 36.2, 0, 0, 1]], dtype=object)

<h3 style="color:brown">Applying Decision tree</h3>

In [36]:
dt.predict(test_input_tnf)    # it predicts that the passenger wouldn't survive

array([0])